# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMM Mini' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMM Mini

  # Rings
  pod 'MKRingProgressView'
  
  # Animation
  pod 'lottie-ios'
  
  # Animation
  pod 'SkeletonView'
  
  # Keyboard
  pod 'IQKeyboardManagerSwift'
  
  # Crop Image
  pod 'TOCropViewController'

end
